const assert=require('node:assert/strict');
const {test}=require('node:test');
const {PROMOTION_TIERS}=require('../../consts/gameConstants');
const TIER_ORDER=Object.keys(PROMOTION_TIERS);
const TIER_LADDER=TIER_ORDER.slice(0,-1).map((f,i)=>{ const n=TIER_ORDER[i+1]; const m=PROMOTION_TIERS[n]?.minOverall??Infinity; return{from:f,to:n,minOverall:m}; });
const NO_CHAMPION_TIERS=['GCS Contender'];
const TITLE_SHOT_DEFAULT={titleWins:3,beltFame:200,beltBadge:'Champion'};
const TITLE_SHOT_BY_TIER={'Amateur':{titleWins:2,beltFame:75,beltBadge:'Amateur Champion'},'Regional Pro':{titleWins:3,beltFame:200,beltBadge:'Champion'},'National':{titleWins:3,beltFame:200,beltBadge:'Champion'},'GCS':{titleWins:3,beltFame:200,beltBadge:'Champion'}};
function getTitleShotConfig(tier){return TITLE_SHOT_BY_TIER[tier]||TITLE_SHOT_DEFAULT;}
function checkPromotion(f2){if(f2.pendingPromotion)return null;const entry=TIER_LADDER.find(t=>t.from===f2.promotionTier);if(!entry)return null;if((f2.overallRating||0)<entry.minOverall)return null;if(NO_CHAMPION_TIERS.includes(f2.promotionTier))return entry.to;f2.pendingPromotion=entry.to;return null;}
const{isUnlocked}=require('../../services/bannerService');
const{CHAMPION_TIERS}=require('../../services/championService');
const FC={id:'FRAME_CHAMP',kind:'frame',unlockAt:{beltsWon:true}};
test('S1a: Amateur OVR 29 no promotion',()=>{ const f={promotionTier:'Amateur',overallRating:29,pendingPromotion:null}; assert.equal(checkPromotion(f),null); assert.equal(f.pendingPromotion,null); });
test('S1b: Amateur OVR 14 new fighter',()=>{ const f={promotionTier:'Amateur',overallRating:14,pendingPromotion:null}; assert.equal(checkPromotion(f),null); assert.equal(f.pendingPromotion,null); });
test('S2a: Amateur OVR 30 gated',()=>{ const f={promotionTier:'Amateur',overallRating:30,pendingPromotion:null}; assert.equal(checkPromotion(f),null); assert.equal(f.pendingPromotion,'Regional Pro'); assert.equal(f.promotionTier,'Amateur'); });
test('S2b: Already pendingPromotion noop',()=>{ const f={promotionTier:'Amateur',overallRating:30,pendingPromotion:'Regional Pro'}; assert.equal(checkPromotion(f),null); assert.equal(f.pendingPromotion,'Regional Pro'); });
test('S3: GCS Contender auto-promotes to GCS',()=>{ const f={promotionTier:'GCS Contender',overallRating:62,pendingPromotion:null}; assert.equal(checkPromotion(f),'GCS'); assert.equal(f.pendingPromotion,null); });
test('S4a: Amateur config titleWins 2 beltFame 75',()=>{ const c=getTitleShotConfig('Amateur'); assert.equal(c.titleWins,2); assert.equal(c.beltFame,75); assert.equal(c.beltBadge,'Amateur Champion'); });
test('S4b: Regional Pro config',()=>{ const c=getTitleShotConfig('Regional Pro'); assert.equal(c.titleWins,3); assert.equal(c.beltFame,200); assert.equal(c.beltBadge,'Champion'); });
test('S4c: National config',()=>{ const c=getTitleShotConfig('National'); assert.equal(c.titleWins,3); assert.equal(c.beltFame,200); assert.equal(c.beltBadge,'Champion'); });
test('S4d: Unknown tier default',()=>{ const c=getTitleShotConfig('Unknown'); assert.equal(c.titleWins,3); assert.equal(c.beltFame,200); assert.equal(c.beltBadge,'Champion'); });
test('S5a: Amateur belt win oldTier before mutation',()=>{ const f={promotionTier:'Amateur',pendingPromotion:'Regional Pro'}; const old=f.promotionTier; f.promotionTier=f.pendingPromotion; const b=getTitleShotConfig(old); assert.equal(b.beltBadge,'Amateur Champion'); assert.equal(b.beltFame,75); });
test('S5b: Regional Pro belt win Champion 200',()=>{ const f={promotionTier:'Regional Pro',pendingPromotion:'National'}; const old=f.promotionTier; f.promotionTier=f.pendingPromotion; const b=getTitleShotConfig(old); assert.equal(b.beltBadge,'Champion'); assert.equal(b.beltFame,200); });
test('S6a: Amateur Champion NOT playerIsChampion',()=>{ assert.equal(['Amateur Champion'].includes('Champion'),false); });
test('S6b: Champion IS playerIsChampion',()=>{ assert.equal(['Champion'].includes('Champion'),true); });
test('S7a: Amateur 0 wins winsNeeded 2',()=>{ assert.equal(Math.max(0,getTitleShotConfig('Amateur').titleWins-0),2); });
test('S7b: Amateur 2 wins winsMet true',()=>{ assert.equal(2>=getTitleShotConfig('Amateur').titleWins,true); });
test('S7c: Regional Pro 2 wins winsNeeded 1',()=>{ assert.equal(Math.max(0,getTitleShotConfig('Regional Pro').titleWins-2),1); });
test('S8a: Amateur 2nd win fires TITLE_SHOT_ELIGIBLE',()=>{ const f={promotionTier:'Amateur',pendingPromotion:'Regional Pro',winsInCurrentTier:2,titleShotCooldown:0}; const fires=!!f.pendingPromotion&&f.winsInCurrentTier===getTitleShotConfig(f.promotionTier).titleWins&&f.titleShotCooldown<=0; assert.equal(fires,true); });
test('S8b: Amateur 1st win no TITLE_SHOT_ELIGIBLE',()=>{ const f={promotionTier:'Amateur',pendingPromotion:'Regional Pro',winsInCurrentTier:1,titleShotCooldown:0}; const fires=!!f.pendingPromotion&&f.winsInCurrentTier===getTitleShotConfig(f.promotionTier).titleWins&&f.titleShotCooldown<=0; assert.equal(fires,false); });
test('S8c: Post belt win pendingPromotion null',()=>{ assert.equal(!!(null),false); });
test('S9a: Amateur Champion only frame NOT unlocked',()=>{ const f={badges:['Amateur Champion'],record:{},notoriety:{peakTier:'PROSPECT'}}; assert.equal(isUnlocked(f,FC),false); });
test('S9b: Champion badge frame IS unlocked',()=>{ const f={badges:['Champion'],record:{},notoriety:{}}; assert.equal(isUnlocked(f,FC),true); });
test('S9c: No badges frame NOT unlocked',()=>{ const f={badges:[],record:{},notoriety:{}}; assert.equal(isUnlocked(f,FC),false); });
test('S10a: Migration filter',()=>{ const all=[{promotionTier:'Amateur',overallRating:30,pendingPromotion:null},{promotionTier:'Amateur',overallRating:35,pendingPromotion:undefined},{promotionTier:'Amateur',overallRating:30,pendingPromotion:'Regional Pro'},{promotionTier:'Amateur',overallRating:29,pendingPromotion:null},{promotionTier:'Regional Pro',overallRating:40,pendingPromotion:null}]; const c=all.filter(x=>x.promotionTier==='Amateur'&&x.overallRating>=30&&x.pendingPromotion==null); assert.equal(c.length,2); });
test('S10b: Migration idempotent',()=>{ const all=[{promotionTier:'Amateur',overallRating:30,pendingPromotion:'Regional Pro'}]; const c=all.filter(x=>x.promotionTier==='Amateur'&&x.overallRating>=30&&x.pendingPromotion==null); assert.equal(c.length,0); });
test('S11: CHAMPION_TIERS has Amateur not GCS Contender',()=>{ assert.ok(CHAMPION_TIERS.includes('Amateur')); assert.ok(CHAMPION_TIERS.includes('Regional Pro')); assert.ok(CHAMPION_TIERS.includes('National')); assert.ok(CHAMPION_TIERS.includes('GCS')); assert.ok(!CHAMPION_TIERS.includes('GCS Contender')); });
test('S12: NO_CHAMPION_TIERS excludes Amateur',()=>{ assert.equal(NO_CHAMPION_TIERS.includes('Amateur'),false); assert.equal(NO_CHAMPION_TIERS.includes('GCS Contender'),true); assert.equal(NO_CHAMPION_TIERS.length,1); });
test('S13a: Turn Pro badge for Regional Pro',()=>{ const o={type:'TitleShot',titleShotMeta:{targetTier:'Regional Pro'}}; const isP=o.type==='TitleShot'&&o.titleShotMeta?.targetTier==='Regional Pro'; assert.equal(isP?'Turn Pro':'Title Shot','Turn Pro'); });
test('S13b: Title Shot badge for National',()=>{ const o={type:'TitleShot',titleShotMeta:{targetTier:'National'}}; const isP=o.type==='TitleShot'&&o.titleShotMeta?.targetTier==='Regional Pro'; assert.equal(isP?'Turn Pro':'Title Shot','Title Shot'); });
test('S14: null champion guard no crash',()=>{ const ch=null; const of=[]; if(ch)of.push(1); assert.equal(of.length,0); });