const assert = require("node:assert");
const { test } = require("node:test");
const SOFT_CAP = 99;
function ensureInventoryShape(f) { if (!f.inventory) f.inventory = {}; var i = f.inventory; if (typeof i.energyShots !== "number") i.energyShots = 0; if (typeof i.energyDrinks !== "number") i.energyDrinks = 0; if (!i.prefightBuffs) i.prefightBuffs = {}; if (!i.usedBuffs) i.usedBuffs = {}; }
var _mm = false; function makeFighter(n, noInv) { _mm = false; var f = { markModified: function() { _mm = true; } }; if (!noInv) f.inventory = { energyDrinks: n }; return f; }
function grant(f, amt) { ensureInventoryShape(f); var cur = f.inventory.energyDrinks; var g = Math.max(0, Math.min(Number(amt) || 0, SOFT_CAP - cur)); if (g > 0) { f.inventory.energyDrinks = cur + g; f.markModified("inventory"); } return g; }
test("1a grant below cap", function() { var f=makeFighter(10); assert.strictEqual(grant(f,5),5); assert.strictEqual(f.inventory.energyDrinks,15); assert.ok(_mm); });
test("1b grant exceeds 99 clamps", function() { var f=makeFighter(97); assert.strictEqual(grant(f,5),2); assert.strictEqual(f.inventory.energyDrinks,99); assert.ok(_mm); });
test("1c at 99 returns 0 no mutation", function() { var f=makeFighter(99); assert.strictEqual(grant(f,1),0); assert.strictEqual(f.inventory.energyDrinks,99); assert.strictEqual(_mm,false); });
test("1d amount 0 returns 0", function() { var f=makeFighter(10); assert.strictEqual(grant(f,0),0); assert.strictEqual(f.inventory.energyDrinks,10); assert.strictEqual(_mm,false); });
test("1e negative returns 0", function() { var f=makeFighter(10); assert.strictEqual(grant(f,-5),0); assert.strictEqual(_mm,false); });
test("1f NaN returns 0", function() { var f=makeFighter(10); assert.strictEqual(grant(f,NaN),0); assert.strictEqual(_mm,false); });
test("1g undefined returns 0", function() { var f=makeFighter(10); assert.strictEqual(grant(f,undefined),0); assert.strictEqual(_mm,false); });
test("1h missing inventory backfilled", function() { var f=makeFighter(0,true); assert.strictEqual(f.inventory,undefined); assert.strictEqual(grant(f,3),3); assert.strictEqual(f.inventory.energyDrinks,3); assert.ok(_mm); });
test("1i inventory missing energyDrinks backfills", function() { var c=false; var f={inventory:{energyShots:2},markModified:function(){c=true;}}; assert.strictEqual(grant(f,4),4); assert.strictEqual(f.inventory.energyDrinks,4); assert.ok(c); });
test("1j helper never calls save", function() { var f=makeFighter(5); f.save=function(){throw new Error("save must not be called");}; assert.doesNotThrow(function(){grant(f,2);}); });
test("2a running clamp 97+2 then 3: second is 0", function() { var f=makeFighter(97); assert.strictEqual(grant(f,2),2); assert.strictEqual(f.inventory.energyDrinks,99); _mm=false; assert.strictEqual(grant(f,3),0); assert.strictEqual(f.inventory.energyDrinks,99); assert.strictEqual(_mm,false); });
test("2b running clamp 95+2 then 3: partial second", function() { var f=makeFighter(95); assert.strictEqual(grant(f,2),2); assert.strictEqual(f.inventory.energyDrinks,97); assert.strictEqual(grant(f,3),2); assert.strictEqual(f.inventory.energyDrinks,99); });
test("2c 50 grants of 2 clamp at 99", function() { var f=makeFighter(0); var t=0; for(var i=0;i<50;i++)t+=grant(f,2); assert.strictEqual(f.inventory.energyDrinks,99); assert.ok(t<=99); });
var ST = {5:1, 10:2, 15:2, 20:3};
test("3a milestones only at 5/10/15/20", function() { [5,10,15,20].forEach(function(m){assert.ok(ST[m]!==undefined,"should have "+m);}); [1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,21].forEach(function(n){assert.strictEqual(ST[n],undefined,"should not have "+n);}); });
test("3b streak 5=1", function() { assert.strictEqual(ST[5],1); });
test("3c streak 10=2", function() { assert.strictEqual(ST[10],2); });
test("3d streak 15=2", function() { assert.strictEqual(ST[15],2); });
test("3e streak 20=3", function() { assert.strictEqual(ST[20],3); });
test("3f loss winStreak 0 no grant", function() { var isWin=false; var g=0; if(isWin&&ST[0])g=999; assert.strictEqual(g,0); });
test("3g draw winStreak 0 no grant", function() { var isWin=false; var ws=isWin?5:0; var g=0; if(isWin&&ST[ws])g=999; assert.strictEqual(g,0); });
test("3h streak 6 not in table", function() { assert.strictEqual(ST[6],undefined); });
test("3i streak 15 milestone exists and positive", function() { assert.ok(ST[15]!==undefined); assert.ok(ST[15]>0); });
test("4a sponsor reads rewardDrinks from contract", function() { var c={rewardDrinks:3,totals:{drinksEarned:0}}; var f=makeFighter(10); var g=0; if(c.rewardDrinks>0){g=grant(f,c.rewardDrinks);c.totals.drinksEarned+=g;} assert.strictEqual(g,3); assert.strictEqual(f.inventory.energyDrinks,13); assert.strictEqual(c.totals.drinksEarned,3); });
test("4b sponsor rewardDrinks=0 grants nothing", function() { var c={rewardDrinks:0,totals:{drinksEarned:0}}; var f=makeFighter(10); var g=0; if(c.rewardDrinks>0)g=grant(f,c.rewardDrinks); assert.strictEqual(g,0); assert.strictEqual(f.inventory.energyDrinks,10); assert.strictEqual(c.totals.drinksEarned,0); });
test("4c sponsor grant only in complete branch", function() { ["active","broken","expired","dropped"].forEach(function(s){ var f=makeFighter(10); var g=0; if(s==="complete")g=grant(f,3); assert.strictEqual(g,0,"status="+s); }); });
test("4d SPONSOR_COMPLETE event carries drinksGranted", function() { var c={rewardDrinks:4,totals:{drinksEarned:0}}; var f=makeFighter(50); var g=0; if(c.rewardDrinks>0){g=grant(f,c.rewardDrinks);c.totals.drinksEarned+=g;} var ev={type:"SPONSOR_COMPLETE",rewardDrinks:g}; assert.strictEqual(ev.rewardDrinks,4); assert.strictEqual(c.totals.drinksEarned,4); });
test("4e at-cap fighter: granted=0 drinksEarned stays 0", function() { var c={rewardDrinks:3,totals:{drinksEarned:0}}; var f=makeFighter(99); var g=0; if(c.rewardDrinks>0){g=grant(f,c.rewardDrinks);c.totals.drinksEarned+=g;} assert.strictEqual(g,0); assert.strictEqual(c.totals.drinksEarned,0); assert.strictEqual(f.inventory.energyDrinks,99); });
test("5a summary drinksGranted has streak+promotion keys", function() { var d={streak:2,promotion:3}; assert.ok("streak" in d); assert.ok("promotion" in d); assert.strictEqual(d.streak,2); assert.strictEqual(d.promotion,3); });
test("5b summary drinksGranted defaults 0", function() { var d={streak:0||0,promotion:0||0}; assert.strictEqual(d.streak,0); assert.strictEqual(d.promotion,0); });
test("5c CareerFeed streakDrinks gate >=10", function() { [{ws:5,sg:1,em:0},{ws:10,sg:2,em:2},{ws:15,sg:2,em:2},{ws:20,sg:3,em:3},{ws:6,sg:0,em:0}].forEach(function(c){assert.strictEqual(c.ws>=10?c.sg:0,c.em,"ws="+c.ws);}); });
test("5d streak 5 drink in summary not in feed meta", function() { var ws=5,sg=1; assert.strictEqual(sg,1); assert.strictEqual(ws>=10?sg:0,0); });
test("5e FightSummary ?? 0 guards missing drinksGranted", function() { var s={}; assert.strictEqual(s.drinksGranted&&s.drinksGranted.streak||0,0); assert.strictEqual(s.drinksGranted&&s.drinksGranted.promotion||0,0); assert.strictEqual((s.sponsorship&&s.sponsorship.events||[]).reduce(function(a,e){return a+(e.rewardDrinks||0);},0),0); });
test("5f event rewardDrinks is clamped not raw", function() { var c={rewardDrinks:5,totals:{drinksEarned:0}}; var f=makeFighter(97); var g=0; if(c.rewardDrinks>0)g=grant(f,c.rewardDrinks); assert.strictEqual(g,2); assert.strictEqual(f.inventory.energyDrinks,99); });
test("6a ensureInventoryShape idempotent", function() { var f=makeFighter(50); ensureInventoryShape(f); ensureInventoryShape(f); assert.strictEqual(f.inventory.energyDrinks,50); });
test("6b acceptOffer snapshot undefined rewardDrinks=0", function() { assert.strictEqual(undefined||0,0); assert.strictEqual(2||0,2); });
test("6c promotion grant once promoted set", function() { var g=0; var promoted={from:"A",to:"B"}; if(promoted){var f=makeFighter(50);g=grant(f,3);} assert.strictEqual(g,3); var g2=0; var p2=null; if(p2)g2=999; assert.strictEqual(g2,0); });
test("7a sponsorCatalog REDLINE_ENERGY=2", function() { var c=require("../../consts/sponsorCatalog"); assert.strictEqual(c.SPONSOR_OFFERS_BY_ID["REDLINE_ENERGY"].rewardDrinks,2); });
test("7b sponsorCatalog CORE_HYDRATE=2", function() { var c=require("../../consts/sponsorCatalog"); assert.strictEqual(c.SPONSOR_OFFERS_BY_ID["CORE_HYDRATE"].rewardDrinks,2); });
test("7c sponsorCatalog PREDATOR_NUTRITION=3", function() { var c=require("../../consts/sponsorCatalog"); assert.strictEqual(c.SPONSOR_OFFERS_BY_ID["PREDATOR_NUTRITION"].rewardDrinks,3); });
test("7d sponsorCatalog BLACKCARD_SPIRITS=4", function() { var c=require("../../consts/sponsorCatalog"); assert.strictEqual(c.SPONSOR_OFFERS_BY_ID["BLACKCARD_SPIRITS"].rewardDrinks,4); });
test("7e APEX_MOUTHGUARDS no rewardDrinks snapshots 0", function() { var c=require("../../consts/sponsorCatalog"); assert.strictEqual(c.SPONSOR_OFFERS_BY_ID["APEX_MOUTHGUARDS"].rewardDrinks||0,0); });
test("7f shopService exports grantEnergyDrinks", function() { var s=require("../../services/shopService"); assert.ok(typeof s.grantEnergyDrinks==="function"); });
test("7g shopService exports ensureInventoryShape", function() { var s=require("../../services/shopService"); assert.ok(typeof s.ensureInventoryShape==="function"); });
test("7h shopService.grantEnergyDrinks pure mutation", function() { var rg=require("../../services/shopService").grantEnergyDrinks; var f={inventory:{energyDrinks:10},markModified:function(){}}; assert.strictEqual(rg(f,5),5); assert.strictEqual(f.inventory.energyDrinks,15); });
test("7i shopService.grantEnergyDrinks clamp real", function() { var rg=require("../../services/shopService").grantEnergyDrinks; var f={inventory:{energyDrinks:98},markModified:function(){}}; assert.strictEqual(rg(f,5),1); assert.strictEqual(f.inventory.energyDrinks,99); });
