/**
 * Octagon Gazette template catalog.
 *
 * Each story type has several template variants. The composer picks one at render
 * time (deterministic per (date, fighterId) — see utils/gazetteRng.js).
 *
 * Variables are written as {VARIABLE_NAME} and substituted by the variable resolver.
 *
 * Each template is { headline, body } — body is null for filler briefs.
 */

const TEMPLATES = {

    // ── PRIORITY 0: Mental Reset Required (overrides almost everything) ──────────
    mental_reset_required: [
        { headline: "MENTAL RESET REQUIRED FOR {FIGHTER}",
          body: "Three losses on the bounce. {FIGHTER} must clear a Mental Reset before the next fight." },
        { headline: "TIME TO BREATHE",
          body: "The losses have piled up for {FIGHTER}. A Mental Reset is mandatory before they fight again." },
        { headline: "PAUSE BUTTON",
          body: "After three straight defeats, {FIGHTER} can't fight until they complete a Mental Reset." },
        { headline: "{FIGHTER} BENCHED UNTIL THE HEAD CLEARS",
          body: "The body's willing but the slate isn't clean. {FIGHTER} stays on the shelf until a Mental Reset is complete." },
        { headline: "NO FIGHT BOOKED — AND THERE WON'T BE",
          body: "Three defeats deep, {FIGHTER} is locked out of the cage until a Mental Reset goes through." },
        { headline: "STEP OFF THE LEDGE, {FIGHTER}",
          body: "Coaches have seen this spiral before. Before {FIGHTER} can sign anything, a Mental Reset comes first." },
    ],

    // ── PRIORITY 1: Event Result ────────────────────────────────────────────────
    event_result_ko: [
        { headline: "{WINNER} DEMOLISHES {LOSER} IN ROUND {ROUND}",
          body: "{EVENT_NAME} delivered a statement finish last night as {WINNER} put {LOSER} away with a devastating stoppage." },
        { headline: "LIGHTS OUT FOR {LOSER} — {WINNER} WINS BY KO",
          body: "It was over in round {ROUND}. {WINNER} landed the shot that ended the night at {EVENT_NAME}." },
        { headline: "BRUTAL STOPPAGE AT {EVENT_NAME}",
          body: "{WINNER} needed just {ROUND} round(s) to finish {LOSER} in one of the year's most emphatic performances." },
        { headline: "ROUND {ROUND} FINISH: {WINNER} OVER {LOSER}",
          body: "The main card at {EVENT_NAME} ended early as {WINNER} secured the KO victory." },
        { headline: "{WINNER} CLOSES THE SHOW EARLY ON {LOSER}",
          body: "The crowd at {EVENT_NAME} barely settled before {WINNER} dropped {LOSER} cold in round {ROUND}." },
        { headline: "ONE SHOT, ONE NIGHT — {WINNER} TAKES IT",
          body: "{LOSER} walked in confident and left horizontal. {WINNER} owns the {EVENT_NAME} highlight reel after a round {ROUND} knockout." },
        { headline: "{EVENT_NAME} ERUPTS AS {WINNER} FINISHES",
          body: "{ROUND} round(s) was all {WINNER} required to separate {LOSER} from the contest and the result." },
    ],
    event_result_sub: [
        { headline: "{WINNER} TAPS OUT {LOSER} IN ROUND {ROUND}",
          body: "A masterclass on the mat at {EVENT_NAME} as {WINNER} secured the submission finish." },
        { headline: "SUBMISSION SPECIALIST {WINNER} DOES IT AGAIN",
          body: "{LOSER} had no answer for {WINNER}'s ground game at {EVENT_NAME}. Tap out in round {ROUND}." },
        { headline: "THE MAT IS {WINNER}'S DOMAIN",
          body: "{EVENT_NAME} saw another dominant submission victory as {WINNER} finished {LOSER} in round {ROUND}." },
        { headline: "TECHNICAL MASTERPIECE AT {EVENT_NAME}",
          body: "{WINNER} forces the tap from {LOSER} in round {ROUND} in a display of elite grappling." },
        { headline: "{WINNER} WRAPS {LOSER} UP AND TURNS OUT THE LIGHTS",
          body: "No panic, no rush. {WINNER} hunted the finish at {EVENT_NAME} and got the tap from {LOSER} in round {ROUND}." },
        { headline: "NO ESCAPE AT {EVENT_NAME}",
          body: "Once it hit the canvas it was academic. {WINNER} submits {LOSER} in round {ROUND} without a wasted motion." },
        { headline: "{WINNER} CHOKES OUT THE COMPETITION",
          body: "{LOSER} fought the grip as long as the body allowed. {WINNER} sealed the submission at {EVENT_NAME} in round {ROUND}." },
    ],
    event_result_dec: [
        { headline: "{WINNER} EDGES {LOSER} OVER THE DISTANCE AT {EVENT_NAME}",
          body: "Three rounds of war ended with the judges favouring {WINNER} in a hard-fought contest." },
        { headline: "DECISION VICTORY FOR {WINNER} AT {EVENT_NAME}",
          body: "{LOSER} pushed the pace but {WINNER} had the answers when it counted." },
        { headline: "CLOSE FIGHT, CLEAR WINNER",
          body: "{WINNER} takes the decision over {LOSER} at {EVENT_NAME} after a grinding, tactical contest." },
        { headline: "JUDGES FAVOUR {WINNER} AFTER THREE ROUNDS",
          body: "It went the distance at {EVENT_NAME} but {WINNER} did enough to take the nod over {LOSER}." },
        { headline: "{WINNER} BANKS THE ROUNDS, TAKES THE NOD AT {EVENT_NAME}",
          body: "No finish, no fireworks, no doubt. {WINNER} out-worked {LOSER} from bell to bell for the decision." },
        { headline: "FIFTEEN HARD MINUTES GO TO {WINNER}",
          body: "{LOSER} never stopped pressing, but {EVENT_NAME} belonged to {WINNER} once the scorecards came in." },
        { headline: "GROUND OUT AND EARNED — {WINNER} OVER {LOSER}",
          body: "A chess match at {EVENT_NAME} tilted {WINNER}'s way, the judges rewarding the busier, smarter night's work." },
    ],

    // ── PRIORITY 2: First Loss + Title Fight Composite ─────────────────────────
    first_loss_in_title: [
        { headline: "FIRST DEFEAT — AND IT WAS FOR THE BELT",
          body: "{OPPONENT} hands {FIGHTER} a maiden professional loss in the {TIER} title fight. A career-defining night." },
        { headline: "THE PERFECT RECORD BREAKS UNDER THE LIGHTS",
          body: "{FIGHTER}'s unbeaten run ends in the {TIER} title fight. {OPPONENT} keeps the belt." },
        { headline: "GOLD ELUDES THE UNDEFEATED",
          body: "{FIGHTER} arrives with a perfect record and leaves with a first loss. {OPPONENT} retains the {TIER} title." },
        { headline: "ONE NIGHT, TWO FIRSTS — DEFEAT AND A TITLE MISS",
          body: "{FIGHTER} reached for the {TIER} belt with a spotless record and walked away with neither. {OPPONENT} saw to that." },
        { headline: "{OPPONENT} SPOILS THE CORONATION",
          body: "The script had {FIGHTER} crowned undefeated. Instead {OPPONENT} kept the {TIER} title and wrote the first loss." },
        { headline: "THE BELT, AND THE ZERO, STAY BEHIND",
          body: "{FIGHTER} leaves the {TIER} title fight with a maiden defeat. {OPPONENT} proved the gap between contender and champion." },
    ],

    // ── PRIORITY 3: Title Fight Result ─────────────────────────────────────────
    title_won: [
        { headline: "NEW CHAMPION CROWNED",
          body: "{FIGHTER} defeats {OPPONENT} to become the {TIER} champion. The belt is theirs." },
        { headline: "THE THRONE IS TAKEN",
          body: "{FIGHTER} dethrones {OPPONENT} in {ROUND} round(s) to claim the {TIER} title." },
        { headline: "CHAMPION. {FIGHTER} IS CHAMPION.",
          body: "The {TIER} division has a new ruler. {FIGHTER} finishes {OPPONENT} and seizes the gold." },
        { headline: "UPSET OF THE YEAR? {FIGHTER} CAPTURES THE {TIER} BELT",
          body: "{OPPONENT} didn't see it coming. {FIGHTER} is the new champion." },
        { headline: "{FIGHTER} TAKES THE GOLD IN {ROUND} ROUND(S)",
          body: "The wait is over. {FIGHTER} finishes {OPPONENT} and walks out of the {TIER} division as its champion." },
        { headline: "LONG LIVE THE NEW {TIER} KING",
          body: "{OPPONENT} held that belt like it was permanent. {FIGHTER} just proved nothing is." },
        { headline: "EVERYTHING CHANGES TONIGHT FOR {FIGHTER}",
          body: "A {TIER} title, a new life. {FIGHTER} beats {OPPONENT} and steps into a different career entirely." },
    ],
    title_lost: [
        { headline: "SO CLOSE, YET SO FAR",
          body: "{FIGHTER} falls short in the title fight against {OPPONENT}. The {TIER} belt remains out of reach." },
        { headline: "{OPPONENT} RETAINS — {FIGHTER} MUST REGROUP",
          body: "A valiant effort from {FIGHTER} but {OPPONENT} proved too strong on the night." },
        { headline: "TITLE SHOT COMES UP SHORT FOR {FIGHTER}",
          body: "{OPPONENT} keeps the {TIER} title. {FIGHTER} returns to the rankings to rebuild." },
        { headline: "NOT YET",
          body: "{FIGHTER} pushes {OPPONENT} but falls short of the {TIER} championship. The hunger remains." },
        { headline: "THE BELT STAYS WITH {OPPONENT}",
          body: "{FIGHTER} had the moment in their hands and {OPPONENT} took it back. The {TIER} crown is still spoken for." },
        { headline: "{ROUND} ROUND(S) SHORT OF THE DREAM",
          body: "{FIGHTER} pushed {OPPONENT} hard, but the {TIER} title demanded more than was there tonight." },
        { headline: "ONE STEP FROM GOLD, ONE STEP TOO FAR",
          body: "{OPPONENT} answered every question {FIGHTER} asked. The {TIER} belt remains a mountain still to climb." },
    ],

    // ── PRIORITY 4: First Loss (standalone) ────────────────────────────────────
    first_loss: [
        { headline: "THE PERFECT RECORD IS GONE",
          body: "{FIGHTER} suffers a first professional loss at the hands of {OPPONENT}. The question now is how they respond." },
        { headline: "ZERO BECOMES ONE",
          body: "{OPPONENT} hands {FIGHTER} their first career defeat. Every great fighter faces this moment." },
        { headline: "FIRST LOSS FOR {FIGHTER}",
          body: "The {RECORD} record takes its first blemish. {OPPONENT} was the one to do it." },
        { headline: "NOBODY GOES FOREVER — {FIGHTER} FALLS",
          body: "{OPPONENT} ends the unbeaten run. How {FIGHTER} responds will define them." },
        { headline: "A DARK NIGHT FOR {FIGHTER}",
          body: "The unbeaten record is no more. {OPPONENT} wins in a defining moment in {FIGHTER}'s career." },
        { headline: "THE ZERO FALLS FOR {FIGHTER}",
          body: "It had to happen eventually. {OPPONENT} is the name on the night {FIGHTER}'s perfect record finally cracked." },
        { headline: "{OPPONENT} WRITES THE FIRST BLEMISH",
          body: "A flawless run ends here. {FIGHTER} takes a debut loss and now the real test — the response — begins." },
        { headline: "UNBEATEN NO MORE",
          body: "{FIGHTER}'s {RECORD} ledger carries its first defeat after {OPPONENT} found the answers nobody else could." },
    ],

    // ── PRIORITY 5: Auto-Promotion ─────────────────────────────────────────────
    auto_promotion: [
        { headline: "{FIGHTER} EARNS THE STEP UP",
          body: "Promoted to the {TIER} division. The stakes just got higher." },
        { headline: "WELCOME TO {TIER}",
          body: "{FIGHTER} ascends to the {TIER} division. A new pool of opponents awaits." },
        { headline: "DIVISION MOVE FOR {FIGHTER}",
          body: "Up and out. {FIGHTER} graduates to the {TIER} ranks." },
        { headline: "{FIGHTER} OUTGROWS THE ROOM",
          body: "There was nothing left to prove down a tier. {FIGHTER} moves up to {TIER} and the level rises with them." },
        { headline: "GRADUATION DAY FOR {FIGHTER}",
          body: "The promotion is official — {TIER} is the new home, and the welcome will not be gentle." },
        { headline: "ONWARD AND UPWARD INTO {TIER}",
          body: "{FIGHTER} earns the bump to the {TIER} ranks. Bigger names, longer odds, brighter lights." },
    ],

    // ── PRIORITY 6: Rank Entry ─────────────────────────────────────────────────
    rank_entry: [
        { headline: "{FIGHTER} ENTERS THE {TIER} RANKINGS AT #{NEW_RANK}",
          body: "Three fights in. {FIGHTER} earns a spot in the {TIER} rankings at #{NEW_RANK}." },
        { headline: "OFFICIALLY RANKED",
          body: "After three fights, {FIGHTER} debuts in the {TIER} rankings at #{NEW_RANK}." },
        { headline: "FROM UNRANKED TO #{NEW_RANK}",
          body: "{FIGHTER} makes their {TIER} ranking debut. The climb begins." },
        { headline: "{FIGHTER} CRACKS THE {TIER} LIST AT #{NEW_RANK}",
          body: "No longer just a name on a card. {FIGHTER} debuts in the {TIER} rankings at #{NEW_RANK}." },
        { headline: "A NUMBER NEXT TO THE NAME",
          body: "{FIGHTER} is officially ranked, opening the {TIER} account at #{NEW_RANK}." },
        { headline: "THE BOARD MAKES ROOM FOR {FIGHTER}",
          body: "Three fights earned it. {FIGHTER} enters the {TIER} rankings at #{NEW_RANK} with plenty more in the tank." },
    ],

    // ── PRIORITY 7: Win Streak Milestone ───────────────────────────────────────
    win_streak: [
        { headline: "{STREAK} AND COUNTING — {FIGHTER} IS ON FIRE",
          body: "The wins keep coming. {FIGHTER} has now strung together {STREAK} consecutive victories." },
        { headline: "CAN ANYONE STOP {FIGHTER}?",
          body: "{STREAK} straight wins. The division is taking notice." },
        { headline: "{FIGHTER} ROLLS TO {STREAK}-FIGHT WIN STREAK",
          body: "Dominant, consistent, relentless. {FIGHTER} continues to build a statement run." },
        { headline: "THE STREAK IS REAL — {FIGHTER} AT {STREAK}",
          body: "What started as a good run is becoming something special. {STREAK} wins in a row for {FIGHTER}." },
        { headline: "UNSTOPPABLE? {FIGHTER} MAKES IT {STREAK}",
          body: "Another win, another step toward the top." },
        { headline: "{STREAK} STRAIGHT AND NO BRAKES IN SIGHT",
          body: "{FIGHTER} keeps cashing wins. {STREAK} in a row now, and the matchmakers are running out of safe options." },
        { headline: "WHO BOOKS THE FIGHT THAT ENDS THIS?",
          body: "{FIGHTER} sits on {STREAK} consecutive victories. So far, nobody's volunteered to be the answer." },
        { headline: "{FIGHTER} TURNS A RUN INTO A REPUTATION",
          body: "{STREAK} wins deep, the conversation has changed. This isn't a hot streak anymore — it's a résumé." },
    ],

    // ── PRIORITY 8: Rank Jump ──────────────────────────────────────────────────
    rank_jump: [
        { headline: "ROCKET UP THE RANKINGS",
          body: "{FIGHTER} jumps from #{OLD_RANK} to #{NEW_RANK} in the {TIER} division after last night's result." },
        { headline: "THE RANKINGS ARE SHIFTING",
          body: "A big move for {FIGHTER}, climbing from #{OLD_RANK} to #{NEW_RANK} in {TIER}." },
        { headline: "#{NEW_RANK} AND RISING",
          body: "{FIGHTER} makes a statement leap up the {TIER} rankings, moving to #{NEW_RANK}." },
        { headline: "EYES ON {FIGHTER}",
          body: "From #{OLD_RANK} to #{NEW_RANK} in one night. The {TIER} division is paying attention." },
        { headline: "{FIGHTER} VAULTS FROM #{OLD_RANK} TO #{NEW_RANK}",
          body: "One result, a fistful of places. {FIGHTER} surges up the {TIER} board and the names above are nervous." },
        { headline: "THE {TIER} LADDER JUST GOT SHAKEN",
          body: "{FIGHTER} climbs to #{NEW_RANK}, leaving #{OLD_RANK} and a few bruised egos in the rear-view." },
        { headline: "BIG NIGHT, BIGGER JUMP FOR {FIGHTER}",
          body: "From #{OLD_RANK} to #{NEW_RANK} in {TIER}. The contenders' circle is suddenly within touching distance." },
    ],

    // ── PRIORITY 9: Last Fight Result (default lead/secondary) ─────────────────
    win_ko: [
        { headline: "KNOCKOUT VICTORY FOR {FIGHTER}",
          body: "{FIGHTER} put {OPPONENT} away in round {ROUND}. Another finish, another step up the rankings." },
        { headline: "{FIGHTER} SENDS {OPPONENT} TO THE CANVAS",
          body: "Brutal and efficient. {FIGHTER} secured the stoppage in round {ROUND}." },
        { headline: "STATEMENT WIN FOR {FIGHTER}",
          body: "{OPPONENT} had no answer for what {FIGHTER} brought. KO finish, round {ROUND}." },
        { headline: "ROUND {ROUND} FINISH — {FIGHTER} OVER {OPPONENT}",
          body: "The fight was stopped in round {ROUND} as {FIGHTER} landed the decisive blow." },
        { headline: "LIGHTS OUT",
          body: "{FIGHTER} ends the night early with a KO victory over {OPPONENT} in round {ROUND}." },
        { headline: "{FIGHTER} FINDS THE OFF SWITCH ON {OPPONENT}",
          body: "It didn't go long. {FIGHTER} located the finish and {OPPONENT} was done in round {ROUND}." },
        { headline: "CLEAN AND COLD — {FIGHTER} GETS THE KO",
          body: "No controversy, no judges, no debate. {FIGHTER} flattened {OPPONENT} in round {ROUND}." },
        { headline: "{ROUND} ROUND(S) WAS ALL {FIGHTER} NEEDED",
          body: "{OPPONENT} came to compete and left on a stretcher of pride. {FIGHTER} closes the show with a knockout." },
    ],
    win_sub: [
        { headline: "{FIGHTER} SUBMITS {OPPONENT} IN ROUND {ROUND}",
          body: "Another tap out. {FIGHTER} continues to impress on the mat." },
        { headline: "THE GROUND IS {FIGHTER}'S HOME",
          body: "{OPPONENT} tapped in round {ROUND} as {FIGHTER} locked in the submission." },
        { headline: "SUBMISSION WIN FOR {FIGHTER} OVER {OPPONENT}",
          body: "Technical, precise, and effective. {FIGHTER} gets the tap in round {ROUND}." },
        { headline: "ROUND {ROUND}: {FIGHTER} FORCES THE TAP",
          body: "{OPPONENT} had no escape as {FIGHTER} secured the submission victory." },
        { headline: "{FIGHTER} WRINGS THE TAP FROM {OPPONENT}",
          body: "Patient hands, no escape. {FIGHTER} hunted the finish and got it in round {ROUND}." },
        { headline: "TAP, SNAP, OR NAP — {OPPONENT} CHOSE WISELY",
          body: "{FIGHTER} locked it tight and {OPPONENT} had nowhere to go. Submission in round {ROUND}." },
        { headline: "THE MAT BELONGS TO {FIGHTER}",
          body: "Once it hit the floor it was a formality. {FIGHTER} submits {OPPONENT} in round {ROUND}." },
    ],
    win_dec: [
        { headline: "{FIGHTER} GRINDS OUT DECISION OVER {OPPONENT}",
          body: "Three rounds of work, one clear winner. Judges score it for {FIGHTER}." },
        { headline: "DECISION WIN FOR {FIGHTER}",
          body: "{OPPONENT} made it competitive but {FIGHTER} did enough to earn the nod." },
        { headline: "JUDGES FAVOUR {FIGHTER} OVER {OPPONENT}",
          body: "A disciplined performance from {FIGHTER} earns the decision victory." },
        { headline: "THE DISTANCE FAVOURS {FIGHTER}",
          body: "{OPPONENT} pushed hard but {FIGHTER} controlled the fight to earn the decision." },
        { headline: "{FIGHTER} OUTPOINTS {OPPONENT} OVER THE DISTANCE",
          body: "Busier, sharper, smarter. {FIGHTER} banked the rounds and the judges agreed." },
        { headline: "NO FINISH, NO PROBLEM FOR {FIGHTER}",
          body: "{OPPONENT} survived to the final bell but {FIGHTER} owned every minute that mattered." },
        { headline: "THE SCORECARDS SMILE ON {FIGHTER}",
          body: "A patient, professional shift from {FIGHTER}, who out-worked {OPPONENT} for the decision." },
    ],
    loss: [
        { headline: "{FIGHTER} SUFFERS DEFEAT AGAINST {OPPONENT}",
          body: "A tough night. {FIGHTER} falls to {OPPONENT} and returns to the gym to regroup." },
        { headline: "SETBACK FOR {FIGHTER}",
          body: "{OPPONENT} proved too much on the night. {FIGHTER} drops the result and reflects." },
        { headline: "BACK TO THE DRAWING BOARD",
          body: "{FIGHTER} loses to {OPPONENT}. The work continues." },
        { headline: "DEFEAT FOR {FIGHTER} AT THE HANDS OF {OPPONENT}",
          body: "{FIGHTER} fought hard but {OPPONENT} had the answers tonight." },
        { headline: "A LESSON LEARNED",
          body: "{FIGHTER} suffers a loss to {OPPONENT}. Every setback is data." },
        { headline: "{OPPONENT} GETS THE BETTER OF {FIGHTER}",
          body: "Not every night goes to plan. {FIGHTER} comes up short against {OPPONENT} and heads back to fix it." },
        { headline: "{FIGHTER} TASTES DEFEAT TONIGHT",
          body: "{OPPONENT} had the sharper edge. {FIGHTER} takes the loss and starts the long walk back." },
        { headline: "THE NIGHT BELONGS TO {OPPONENT}",
          body: "{FIGHTER} gave what they had; it wasn't enough against {OPPONENT}. The rebuild starts now." },
    ],

    // ── PRIORITY 10: Division Spotlight (fallback lead) ────────────────────────
    spotlight_ranked: [
        { headline: "THE {TIER} DIVISION AWAITS",
          body: "{FIGHTER} sits at #{RANK} and the path forward is clear. Get back in the gym." },
        { headline: "WHAT'S NEXT FOR {FIGHTER}?",
          body: "Sitting at #{RANK} in {TIER}, the next fight could change everything." },
        { headline: "THE DIVISION KEEPS MOVING",
          body: "{FIGHTER} is #{RANK} in {TIER}. Every day without a fight is a day others are catching up." },
        { headline: "#{RANK} ISN'T A DESTINATION FOR {FIGHTER}",
          body: "Holding #{RANK} in {TIER} is fine for some. {FIGHTER} didn't come this far to stop here." },
        { headline: "THE CLOCK TICKS ON {FIGHTER}",
          body: "Ranked #{RANK} in {TIER} and idle. Belts don't fall to the fighter sitting still." },
        { headline: "FROM #{RANK}, EVERY DIRECTION IS A FIGHT",
          body: "{FIGHTER} occupies #{RANK} in {TIER}. Above are targets, below are sharks. Time to move." },
    ],
    spotlight_unranked: [
        { headline: "THE JOURNEY BEGINS",
          body: "{FIGHTER} is unranked and hungry. The {TIER} division won't know what hit it." },
        { headline: "UNRANKED. FOR NOW.",
          body: "{FIGHTER} has everything to prove in the {TIER} division. Time to get to work." },
        { headline: "A CAREER IN MOTION",
          body: "{FIGHTER} is building something in the {TIER} division. The rankings are within reach." },
        { headline: "NO RANKING, ALL AMBITION",
          body: "{FIGHTER} hasn't cracked the {TIER} board yet — but unranked is just a starting line, not a verdict." },
        { headline: "{FIGHTER} KNOCKS ON THE DOOR",
          body: "The {TIER} rankings are right there. {FIGHTER} only needs the results to be let in." },
        { headline: "BUILDING FROM ZERO IN {TIER}",
          body: "{FIGHTER} is unranked and unbothered. The whole {TIER} division is one good run away from learning the name." },
    ],

    // ── SECONDARY / FILLER STORIES ─────────────────────────────────────────────

    fame_tier_up: [
        { headline: "{FIGHTER} ASCENDS TO {FAME_TIER}",
          body: "The fans are taking notice. {FIGHTER}'s fame has climbed into the {FAME_TIER} bracket." },
        { headline: "RECOGNITION GROWS",
          body: "{FIGHTER} reaches {FAME_TIER} status. The buzz around the name is real." },
        { headline: "INTO {FAME_TIER}",
          body: "Notoriety check: {FIGHTER} just moved up to {FAME_TIER}." },
        { headline: "{FIGHTER} GRADUATES TO {FAME_TIER}",
          body: "The room knows the name now. {FIGHTER} climbs into the {FAME_TIER} bracket and the spotlight follows." },
        { headline: "A BIGGER STAGE FINDS {FIGHTER}",
          body: "Fame catches up to form. {FIGHTER} steps up to {FAME_TIER}, and more eyes mean more pressure." },
        { headline: "{FAME_TIER} — AND THE NAME KEEPS GROWING",
          body: "{FIGHTER} crosses into {FAME_TIER}. From here, the cameras don't need an introduction." },
    ],

    notoriety_gained: [
        { headline: "THE BUZZ IS BUILDING",
          body: "{FIGHTER}'s notoriety sits at {NOTORIETY}. The fans are watching." },
        { headline: "FAME ON THE RISE FOR {FIGHTER}",
          body: "Up {CHANGE} notoriety points." },
        { headline: "PEOPLE ARE TALKING ABOUT {FIGHTER}",
          body: "Notoriety now at {NOTORIETY}." },
        { headline: "{FIGHTER} IS THE NAME ON EVERY LIP",
          body: "Notoriety up {CHANGE} this week, sitting at {NOTORIETY}. The buzz has legs." },
        { headline: "THE HYPE MACHINE FINDS A NEW FAVOURITE",
          body: "{CHANGE} notoriety and climbing. {FIGHTER} is officially worth talking about." },
        { headline: "STOCK RISING ON {FIGHTER}",
          body: "Up {CHANGE} on the notoriety meter to {NOTORIETY}. The market likes what it sees." },
    ],
    notoriety_lost: [
        { headline: "FADING FROM THE SPOTLIGHT",
          body: "{FIGHTER}'s notoriety dips to {NOTORIETY}. Results on the canvas are the only cure." },
        { headline: "THE BUZZ COOLS FOR {FIGHTER}",
          body: "Down {CHANGE} notoriety. Time to make some noise." },
        { headline: "QUIET SPELL FOR {FIGHTER}",
          body: "Notoriety at {NOTORIETY}. The fans need a reason to keep talking." },
        { headline: "{FIGHTER} SLIPS FROM THE CONVERSATION",
          body: "Notoriety down {CHANGE} to {NOTORIETY}. Out of sight is dangerously close to out of mind." },
        { headline: "THE SPOTLIGHT WANDERS OFF {FIGHTER}",
          body: "A move of {CHANGE} on the notoriety board drops {FIGHTER} to {NOTORIETY}. A statement win would fix it fast." },
        { headline: "{FIGHTER}'S STOCK COOLS",
          body: "Notoriety shifts {CHANGE} to {NOTORIETY}. The fans are fickle — time to remind them why." },
    ],

    nemesis_set: [
        { headline: "A RIVALRY IS BORN",
          body: "{OPPONENT} just handed {FIGHTER} a loss. A grudge has officially started." },
        { headline: "{FIGHTER} HAS A NEW NEMESIS",
          body: "{OPPONENT}. Remember the name." },
        { headline: "BAD BLOOD HAS A NAME NOW",
          body: "{OPPONENT} beat {FIGHTER} and earned something worse than a win — a grudge. This one isn't finished." },
        { headline: "{FIGHTER} WON'T FORGET {OPPONENT}",
          body: "Some losses sting. This one sticks. {FIGHTER} marks {OPPONENT} as unfinished business." },
    ],
    nemesis_cleared: [
        { headline: "REVENGE SERVED",
          body: "{FIGHTER} settles the score with {OPPONENT}. Nemesis cleared." },
        { headline: "{FIGHTER} GETS THE WIN BACK",
          body: "The grudge is over. {FIGHTER} defeats {OPPONENT}." },
        { headline: "THE DEBT IS PAID IN FULL",
          body: "{FIGHTER} hunted down {OPPONENT} and collected. The nemesis is no more." },
        { headline: "{FIGHTER} CLOSES THE BOOK ON {OPPONENT}",
          body: "What was owed has been settled. {FIGHTER} beats {OPPONENT} and walks away even." },
    ],

    beef_lapsed: [
        { headline: "GRUDGE FIZZLES OUT",
          body: "{FIGHTER}'s beef with {OPPONENT} expired without a fight. The talk costs fame." },
        { headline: "ALL TALK, NO ACTION",
          body: "The beef with {OPPONENT} timed out. Fame penalty applied." },
    ],

    sponsorship_new: [
        { headline: "SPONSOR INTEREST FOR {FIGHTER}",
          body: "{SPONSOR_NAME} has reached out with a sponsorship offer." },
        { headline: "BRANDS ARE WATCHING",
          body: "A new deal from {SPONSOR_NAME} lands on {FIGHTER}'s desk." },
        { headline: "COMMERCIAL APPEAL",
          body: "{FIGHTER} attracts interest from {SPONSOR_NAME}." },
    ],
    sponsorship_clause: [
        { headline: "BONUS UNLOCKED",
          body: "{FIGHTER} triggered a clause with {SPONSOR_NAME}." },
        { headline: "CLAUSE ACTIVATED",
          body: "{SPONSOR_NAME} clause triggered — {FIGHTER} earns the bonus." },
    ],
    sponsorship_expiring: [
        { headline: "DEAL RUNNING OUT",
          body: "{FIGHTER}'s contract with {SPONSOR_NAME} is nearing its end." },
        { headline: "SPONSORSHIP EXPIRY AHEAD",
          body: "{SPONSOR_NAME} deal expires soon." },
    ],

    record_milestone: [
        { headline: "BY THE NUMBERS — {FIGHTER} HITS {MILESTONE_LABEL}",
          body: "The stats tell the story. {FIGHTER}'s record stands at {RECORD}." },
        { headline: "{MILESTONE_LABEL} FOR {FIGHTER}",
          body: "A career marker reached. {RECORD} and still going." },
        { headline: "MILESTONE ALERT: {FIGHTER} AT {MILESTONE_LABEL}",
          body: "Record now reads {RECORD}." },
        { headline: "CAREER LANDMARK FOR {FIGHTER}",
          body: "{MILESTONE_LABEL} reached. {RECORD} on the books." },
        { headline: "{FIGHTER} STAMPS {MILESTONE_LABEL} INTO THE LEDGER",
          body: "Milestones don't lie. {FIGHTER}'s record reads {RECORD} and the ink keeps flowing." },
        { headline: "ANOTHER MARKER FALLS FOR {FIGHTER}",
          body: "{MILESTONE_LABEL} is on the board now, with the record at {RECORD} and no sign of slowing." },
        { headline: "THE RÉSUMÉ GROWS — {MILESTONE_LABEL}",
          body: "{FIGHTER} hits {MILESTONE_LABEL}. {RECORD} and counting, one fight at a time." },
    ],

    gym_session: [
        { headline: "HOURS IN THE GYM ADDING UP", body: null },
        { headline: "THE WORK IS REAL", body: null },
        { headline: "DEDICATED", body: null },
    ],
    gym_perk: [
        { headline: "GYM LOYALTY PAYS OFF", body: null },
        { headline: "NEW BENEFIT AT {GYM_NAME}", body: null },
    ],

    comeback: [
        { headline: "TOUGH TIMES FOR {FIGHTER}",
          body: "{LOSS_STREAK} losses in a row. The gym is the only answer." },
        { headline: "BACK AGAINST THE WALL",
          body: "{FIGHTER} has dropped {LOSS_STREAK} straight. The critics are circling." },
        { headline: "CHARACTER BUILDING MOMENTS",
          body: "{LOSS_STREAK} consecutive losses for {FIGHTER}. This is where careers are defined." },
        { headline: "DARK SPELL FOR {FIGHTER}",
          body: "{LOSS_STREAK} straight defeats. The comeback story is waiting to be written." },
        { headline: "{FIGHTER} STARES DOWN THE SLIDE",
          body: "{LOSS_STREAK} on the trot. This is the stretch where careers either break or harden." },
        { headline: "THE ONLY WAY OUT IS THROUGH",
          body: "{LOSS_STREAK} straight losses for {FIGHTER}. Nobody writes the comeback chapter without one of these first." },
        { headline: "ROCK BOTTOM HAS A BASEMENT — AND A LADDER",
          body: "{FIGHTER} is {LOSS_STREAK} defeats deep. The fall is documented. The climb is the story worth telling." },
    ],

    // ── SIDEBAR GROUPS (v2.0 — seeded headline variation) ──────────────────────
    // Each variant is { headline } only; body is composed in the builder.
    sidebar_rankings_ranked: [
        { headline: "#{RANK} IN THE {TIER} DIVISION" },
        { headline: "CLIMBING THE {TIER} RANKINGS" },
        { headline: "{TIER} BOARD: HOLDING AT #{RANK}" },
    ],
    sidebar_rankings_unranked: [
        { headline: "UNRANKED — {N} FIGHTS FROM THE BOARD" },
        { headline: "KNOCKING ON THE {TIER} RANKINGS" },
        { headline: "{N} FIGHTS UNTIL THE RANKINGS OPEN" },
    ],
    sidebar_nemesis: [
        { headline: "{OPP} — UNFINISHED BUSINESS" },
        { headline: "THE GRUDGE AGAINST {OPP} LIVES" },
        { headline: "REVENGE IS A FIGHT AWAY — {OPP}" },
    ],
    sidebar_fight_offers: [
        { headline: "NEW OFFERS WAITING" },
        { headline: "OPPONENTS READY TO SIGN" },
        { headline: "THE MATCHMAKERS HAVE BEEN BUSY" },
    ],
    sidebar_pvp: [
        { headline: "THE LADDER IS CALLING" },
        { headline: "DIVISION POINTS WON'T EARN THEMSELVES" },
    ],
    sidebar_injuries: [
        { headline: "INJURY ALERT: {LABEL}" },
        { headline: "RECOVERY MODE — {LABEL}" },
        { headline: "MEDICAL UPDATE: {LABEL}" },
    ],
    sidebar_gym: [
        { headline: "GYM MASTERY — RANK {RANK}" },
        { headline: "THE WORK CONTINUES AT THE GYM" },
        { headline: "MASTERY GRINDS ON — RANK {RANK}" },
    ],
    sidebar_contracts: [
        { headline: "SPONSOR UPDATE: {BRAND}" },
        { headline: "CONTRACT IN PLAY — {BRAND}" },
    ],
    sidebar_fame: [
        { headline: "FAME: {TIER} TIER" },
        { headline: "{TIER} TIER — THE NAME IS GROWING" },
    ],
    sidebar_spotlight: [
        { headline: "THE DIVISION KEEPS MOVING" },
        { headline: "NO FIGHT IS A FIGHT LOST" },
        { headline: "EVERY DAY IDLE IS A DAY BEHIND" },
    ],

    // ── SECONDARY GROUPS (v2.0) ────────────────────────────────────────────────
    secondary_camp_report: [
        { headline: "CAMP REPORT: THE WORK BEHIND THE WIN" },
        { headline: "INSIDE THE FIGHT CAMP" },
        { headline: "PREPARATION TELLS ITS OWN STORY" },
    ],
    secondary_gym_milestone: [
        { headline: "{SESSIONS} TRAINING SESSIONS LOGGED" },
        { headline: "THE GRIND HITS {SESSIONS} SESSIONS" },
        { headline: "MILESTONE: {SESSIONS} SESSIONS IN THE GYM" },
    ],
    secondary_badge: [
        { headline: "NEW BADGE EARNED" },
        { headline: "ACHIEVEMENT UNLOCKED" },
        { headline: "ANOTHER ONE FOR THE CABINET" },
    ],
};

module.exports = { TEMPLATES };
