const mongoose = require("mongoose");
const { WEIGHT_CLASSES, STYLES, FIGHT_STRATEGIES } = require("../consts/gameConstants");

const statSchema = { type: Number, min: 1, max: 100, default: 10 };

const opponentSchema = new mongoose.Schema({
    name: { type: String, required: true },
    nickname: { type: String, default: null },
    weightClass: { type: String, enum: WEIGHT_CLASSES, required: true },
    style: { type: String, enum: Object.keys(STYLES), required: true },
    strategy: { type: String, enum: Object.keys(FIGHT_STRATEGIES), default: null },
    promotionTier: { type: String, required: true },
    str: statSchema, spd: statSchema, leg: statSchema, wre: statSchema,
    gnd: statSchema, sub: statSchema, chn: statSchema, fiq: statSchema,
    overallRating: { type: Number, required: true },
    // Ranking System v1.0 — fixedRank is the NPC's permanent position in the ranked roster
    // for their (tier, weightClass). 1 = champion. Never changes after seed.
    fixedRank:    { type: Number, default: null },
    // Champion system
    isChampion:   { type: Boolean, default: false },
    championTier: { type: String, default: null },
    record: {
        wins: { type: Number, default: 0 },
        losses: { type: Number, default: 0 },
        draws: { type: Number, default: 0 },
    },
    // Pre-generated fight history used for the Fighter Report card.
    // Generated by scripts/migrateCampHistory.js based on style and stats.
    fightHistory: [{
        result: { type: String, enum: ['win', 'loss', 'draw'] },
        method: { type: String }, // 'KO/TKO' | 'Submission' | 'Decision' | 'Loss (KO/TKO)' | etc.
        round:  { type: Number, default: 1 },
        _id: false,
    }],
}, { timestamps: true });

opponentSchema.index({ promotionTier: 1, weightClass: 1, overallRating: 1 });
// Ranking System v1.0 index — query the ranked roster for a (tier, weightClass) pair
// sorted by rank. Unique to prevent two NPCs sharing a rank in the same roster.
opponentSchema.index({ promotionTier: 1, weightClass: 1, fixedRank: 1 }, {
    unique: true,
    partialFilterExpression: { fixedRank: { $type: "number" } },
});

const Opponent = mongoose.model("Opponent", opponentSchema);
module.exports = Opponent;
